POST http://127.0.0.1:8000/students HTTP/1.1
Content-Type: application/json

{
    "name": "Daniel",
    "id": "1004333",
    "gpa": 4.0
}

###
# a student with these details will be added into the dataset
# which will also be shown in the previous sortBy,limit,offset queries in the right conditions
