POST http://127.0.0.1:8000/students HTTP/1.1
Content-Type: application/json

{
    "name": "",
    "id": "1004111",
    "gpa": 4.1
}

# throw error 400 as bad request due to missing field
# function will return an error of "Missing name" as well