version: "3.9"
services:
  test-client:
    build: test-client
    image: 50012-lab1-test-client
    volumes:
      - type: volume
        source: nginx-logs
        target: /var/log/nginx
      - type: volume
        source: fastapi-logs
        target: /var/log/fastapi/
      - type: bind
        source: ./nginx-server/html
        target: /var/html
        read_only: true
      - type: bind
        source: ./test-client/result
        target: /var/log/pytest
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PROXY_HOST=proxy
      - PROXY_PORT=8080
      # Run basic tests only
      - PYTEST_TESTS=basic_test.py
      # Run smoke tests only
      # - PYTEST_TESTS=smoke_test.py
      # Default test options
      # - PYTEST_ADDOPTS=-rA --tb=short
      # Shorter version for basic tests, only sample a subset of static files
      - PYTEST_ADDOPTS=-rA --tb=short --proxytest-nginx-static-files-n-samples=3
    depends_on:
      - proxy
      - fastapi-server
      - nginx-server
    restart: "no"
    stop_grace_period: "1s"
  proxy:
    build: proxy
    image: 50012-lab1-test-proxy
    volumes:
      - type: bind
        source: ./proxy/app
        target: /app
      - type: bind
        source: ./proxy/logs
        target: /var/log/proxy/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - nginx-server
    ports:
      - "8080:8080"
      - "3000:3000"
    stop_grace_period: "3s"
  proxy-wireshark:
    image: linuxserver/wireshark
    network_mode: "service:proxy"
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    depends_on:
      - proxy
  nginx-server:
    image: openresty/openresty
    volumes:
      - type: bind
        source: nginx-server/html
        target: /usr/local/openresty/nginx/html
        read_only: true
      - type: bind
        source: ./nginx-server/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: volume
        source: nginx-logs
        target: /var/log/nginx/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8000:80"
  fastapi-server:
    build: fastapi-server
    image: 50012-lab1-fastapi-server
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    environment:
      DEBUG: 1
    volumes:
      - ./fastapi-server/app:/code/app
      - type: volume
        source: fastapi-logs
        target: /var/log/fastapi/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
volumes:
  nginx-logs:
    name: nginx-logs
  fastapi-logs:
    name: fastapi-logs